opc_data = {
    "Continue": True,
    "Encoder_conveyor": 629,
    "Encoder_conveyor1": True,
    "FillpumpNo1": False,
    "FillpumpNo2": False,

    "LH_ASN": 3838,
    "LH_ASN_M": 3838,
    "LH_BN": 16122,
    "LH_BN_M": 16122,
    "LH_FillingPressure": 0,
    "LH_FillingPressure_M": 0,
    "LH_FillingVolume": 0,
    "LH_FillingVolume_M": 0,
    "LH_hz": 0.0,
    "LH_PGNum": 19,
    "LH_PGNum_M": 19,
    "LH_pumpfilling_pressure": 2718,
    "LH_StepNum": 0,
    "LH_StepNum_M": 0,
    "LH_Tricker": False,
    "LH_Tricker_M": False,
    "LH_Vacuum": 0,
    "LH_Vacuum_M": 0,

    "Machine_fault": False,
    "Master_on": True,

    "RH_ASN": 3839,
    "RH_ASN_M": 3839,
    "RH_BN": 16016,
    "RH_BN_M": 16016,
    "RH_encoder": 629,
    "RH_filling_pressure": 2759,
    "RH_filling_volume": 1000,
    "RH_FillingPressure": 0,
    "RH_FillingPressure_M": 0,
    "RH_FillingVolume": 0,
    "RH_FillingVolume_M": 0,
    "RH_gun_vacuum": 94,
    "RH_hz": 10.8,
    "RH_PGNum": 12,
    "RH_PGNum_M": 12,
    "RH_pumpfilling_pressure": 2759,
    "RH_StepNum": 1,
    "RH_StepNum_M": 1,
    "RH_Tricker": True,
    "RH_Tricker1": False,
    "RH_Tricker_M": True,
    "RH_Vaccum": 94,
    "RH_Vaccum_M": 93,
    "RH_vacuum_pump": 42,
}